spring.application.name=FinaSplitter
spring.data.mongodb.uri=mongodb+srv://milosznejbauer_db_user:VmBKyxH8d28n8jqW@finasplitter.nrgwqes.mongodb.net/FinaSplitter
google.api.key=AIzaSyD5aUeBKsnNpvqCjzsqgR7575pC7j4ngEM